### ISSUE TITLE
npm/node installation problem 

### ISSUE THREAD

**Issue by sidouglas** [Dafrok/vue-iscroll-view#26]
```
 npm install

> fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.1.tgz install /Users/simon/Desktop/vue-iscroll-view/node_modules/fsevents
> node install

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/Cellar/node/8.4.0/bin/node',
node-pre-gyp verb cli   '/Users/simon/Desktop/vue-iscroll-view/node_modules/fsevents/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@https://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.6.33.tgz
node-pre-gyp info using node@8.4.0 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack TypeError: Cannot read property 'version' of null
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/simon/Desktop/vue-iscroll-view/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:270:32)
node-pre-gyp ERR! stack     at install (/Users/simon/Desktop/vue-iscroll-view/node_modules/fsevents/node_modules/node-pre-gyp/lib/install.js:168:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/simon/Desktop/vue-iscroll-view/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:50:37)
node-pre-gyp ERR! stack     at run (/Users/simon/Desktop/vue-iscroll-view/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/simon/Desktop/vue-iscroll-view/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:573:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:584:10)
node-pre-gyp ERR! stack     at Module.load (module.js:507:32)
node-pre-gyp ERR! stack     at tryModuleLoad (module.js:470:12)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:462:3)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/8.4.0/bin/node" "/Users/simon/Desktop/vue-iscroll-view/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/simon/Desktop/vue-iscroll-view/node_modules/fsevents
node-pre-gyp ERR! node -v v8.4.0
node-pre-gyp ERR! node-pre-gyp -v vhttps://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.6.33.tgz
node-pre-gyp ERR! not ok 
Cannot read property 'version' of null
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.1.tgz (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.1.tgz install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 919 packages in 11.308s
```

**Comment by Dafrok** [comment]
I think you might try to change a registry.
